server:
  port: 8080
spring:
  config:
    import:
      - optional:aws-secretsmanager:crediya-secrets
  application:
    name: "CrediYa"
  devtools:
    add-properties: false
adapters:
  r2dbc:
    host: "${r2dbcHost}"
    port: "${r2dbcPort}"
    database: "${r2dbcDataBase}"
    schema: "${r2dbcSchema}"
    username: "${r2dbcUsername}"
    password: "${r2dbcPassword}"
    options:
      sslMode: require
    pool:
      enabled: true
      initial-size: 20
      max-size: 100
      maxLifeTime: -1
      validation-query: "SELECT 1"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "${allowedOrigins}"
aws:
  region: "us-east-1"

jwt:
  secret: "${jwtSecret}"
  expiration: 3600